# Generated by Django 4.0.6 on 2022-07-07 17:33

from django.db import migrations, models
try:
    from django.db.models import JSONField
except ImportError:
    from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_field', models.CharField(max_length=255)),
                ('user_data', models.JSONField()),
            ],
        ),
    ]
